Added: TransferFilterParams for Searching Transfer feature
omise/omise-swift pull request #2
Opened 2016-12-19 08:24 UTC by pitiphong-p

2016-12-19 10:09 UTC, chakrit requested changes

2016-12-19 10:09 UTC, chakrit commented on OmiseSwift/CurrencyDataConverter.swift
> +public class CurrencyDataConverter: Converter {
Just `CurrencyConverter` suffice?

2016-12-19 10:52 UTC, pitiphong-p commented on OmiseSwift/CurrencyDataConverter.swift
> +public class CurrencyDataConverter: Converter {
I thought about this name at first and then I realized that `Will the API consumer think that this class is a `currency converter` which convert money between currencies?` So I think it should be named with other name

2016-12-22 11:25 UTC, chakrit commented on OmiseSwift/CurrencyDataConverter.swift
> +public class CurrencyDataConverter: Converter {
`Data` is still pretty generic na. Maybe `CurrencyFieldConverter`

2016-12-22 11:25 UTC, pitiphong-p commented on OmiseSwift/CurrencyDataConverter.swift
> +public class CurrencyDataConverter: Converter {
Umm SGTM

2016-12-22 11:27 UTC, pitiphong-p commented on OmiseSwift/CurrencyDataConverter.swift
> +public class CurrencyDataConverter: Converter {
Done :)

2016-12-22 11:27 UTC, chakrit approved these changes

2016-12-22 11:29 UTC, merged